package com.aalekh.aalekh.report.custommetrics

import com.aalekh.aalekh.model.CustomMetric
import com.aalekh.aalekh.model.CustomMetricReport
import kotlinx.serialization.json.Json

/**
 * Renders a [CustomMetricReport] as the two local artefacts `aalekhMetrics` writes:
 *
 * - [markdown] - a reviewable summary: system-wide metrics in one table, then a per-module table for
 *   each metric that carries module values (worst/highest first), plus any provider failures.
 * - [json] - the same data machine-readable.
 *
 * Both are pure string transforms - no Gradle, no I/O.
 */
public object CustomMetricReportGenerator {

    private val prettyJson = Json {
        prettyPrint = true
        encodeDefaults = true
    }

    /** Serialises the report to pretty-printed JSON. */
    public fun json(report: CustomMetricReport): String =
        prettyJson.encodeToString(CustomMetricReport.serializer(), report)

    /** Renders the report as a Markdown document. */
    public fun markdown(report: CustomMetricReport, projectName: String): String = buildString {
        appendLine("# $projectName - custom metrics (Aalekh SPI)")
        appendLine()
        if (report.metrics.isEmpty() && report.providerFailures.isEmpty()) {
            appendLine(
                "_No custom metric providers were discovered on the plugin classpath. Register one by " +
                    "shipping a `MetricProvider` implementation with a " +
                    "`META-INF/services/com.aalekh.aalekh.analysis.spi.MetricProvider` entry._"
            )
            return@buildString
        }
        appendLine(
            "_Generated by [Aalekh](https://github.com/shivathapaa/aalekh) from the custom-metric SPI " +
                "(`MetricProvider`). Values are produced by third-party providers on the build classpath._"
        )
        appendLine()
        appendSystemTable(report.metrics)
        appendModuleTables(report.metrics)
        appendFailures(report.providerFailures)
    }

    private fun StringBuilder.appendSystemTable(metrics: List<CustomMetric>) {
        val systemMetrics = metrics.filter { it.systemValue != null }
        appendLine("## System metrics")
        appendLine()
        if (systemMetrics.isEmpty()) {
            appendLine("_None._")
            appendLine()
            return
        }
        appendLine("| Metric | Value | Description |")
        appendLine("|--------|------:|-------------|")
        systemMetrics.forEach { metric ->
            val value = formatWithUnit(metric.systemValue ?: 0.0, metric.unit)
            appendLine("| ${metric.displayName} | $value | ${metric.description} |")
        }
        appendLine()
    }

    private fun StringBuilder.appendModuleTables(metrics: List<CustomMetric>) {
        val perModule = metrics.filter { it.moduleValues.isNotEmpty() }
        if (perModule.isEmpty()) return
        appendLine("## Per-module metrics")
        appendLine()
        perModule.forEach { metric -> appendModuleTable(metric) }
    }

    private fun StringBuilder.appendModuleTable(metric: CustomMetric) {
        val header = if (metric.unit.isBlank()) metric.displayName else "${metric.displayName} (${metric.unit})"
        appendLine("### $header")
        appendLine()
        if (metric.description.isNotBlank()) {
            appendLine("_${metric.description}_")
            appendLine()
        }
        appendLine("| Module | Value |")
        appendLine("|--------|------:|")
        val ranked = metric.moduleValues.entries.sortedWith(
            compareByDescending<Map.Entry<String, Double>> { it.value }.thenBy { it.key }
        )
        ranked.take(MAX_MODULE_ROWS).forEach { (path, value) ->
            appendLine("| `$path` | ${format(value)} |")
        }
        if (ranked.size > MAX_MODULE_ROWS) {
            appendLine("| _… and ${ranked.size - MAX_MODULE_ROWS} more_ | |")
        }
        appendLine()
    }

    private fun StringBuilder.appendFailures(failures: List<String>) {
        if (failures.isEmpty()) return
        appendLine("## Provider notes")
        appendLine()
        appendLine("_These providers were skipped; the rest still ran._")
        appendLine()
        failures.forEach { appendLine("- $it") }
        appendLine()
    }

    private fun formatWithUnit(value: Double, unit: String): String =
        if (unit.isBlank()) format(value) else "${format(value)} $unit"

    /**
     * Locale-independent number formatting: whole numbers print without decimals (`42`), everything
     * else to two decimals (`3.14`, `-0.50`).
     */
    private fun format(value: Double): String {
        if (value.isNaN() || value.isInfinite()) return value.toString()
        val rounded = Math.round(value * HUNDRED)
        return when {
            rounded % HUNDRED_INT == 0L -> (rounded / HUNDRED_INT).toString()
            else -> {
                val sign = if (rounded < 0) "-" else ""
                val abs = Math.abs(rounded)
                "$sign${abs / HUNDRED_INT}.${(abs % HUNDRED_INT).toString().padStart(2, '0')}"
            }
        }
    }

    private const val HUNDRED = 100.0
    private const val HUNDRED_INT = 100L
    private const val MAX_MODULE_ROWS = 25
}
