package com.aalekh.aalekh.report.dot

import com.aalekh.aalekh.model.ModuleDependencyGraph

/**
 * Renders a [ModuleDependencyGraph] as a [Graphviz](https://graphviz.org) `digraph` definition (DOT).
 *
 * DOT is the lingua franca of graph tooling: `dot -Tsvg`, `dot -Tpng`, Gephi, and countless viewers
 * consume it. Like the Mermaid export it is plain text and deterministic - nodes are emitted in sorted
 * path order so the same graph always produces byte-identical output that diffs cleanly in review.
 *
 * Output shape:
 * - `digraph` with one `box` node per module, filled with its module-type colour.
 * - Production edges are solid; test-only edges are dashed.
 * - Parallel edges between the same pair collapse into one link (solid wins over dashed).
 */
public object DotGraphGenerator {

    /** Returns the DOT definition for [graph]. */
    public fun generate(graph: ModuleDependencyGraph): String = buildString {
        appendLine("// Generated by Aalekh - https://github.com/shivathapaa/aalekh")
        appendLine("// Solid edges are production dependencies; dashed edges are test-only.")
        appendLine("digraph Aalekh {")
        appendLine("  rankdir=TB;")
        appendLine("  node [shape=box, style=filled, fontcolor=\"#ffffff\"];")

        graph.modules.sortedBy { it.path }.forEach { module ->
            appendLine("  ${quote(module.path)} [fillcolor=${quote(module.type.color)}];")
        }

        collapseEdges(graph).forEach { edge ->
            val style = if (edge.testOnly) " [style=dashed]" else ""
            appendLine("  ${quote(edge.from)} -> ${quote(edge.to)}$style;")
        }

        append("}")
    }

    private fun collapseEdges(graph: ModuleDependencyGraph): List<CollapsedEdge> =
        graph.edges
            .filter { it.from != it.to }
            .groupBy { it.from to it.to }
            .map { (pair, edges) -> CollapsedEdge(pair.first, pair.second, testOnly = edges.all { it.isTest }) }
            .sortedWith(compareBy({ it.from }, { it.to }))

    /** DOT identifiers are double-quoted; escape embedded quotes and newlines. */
    private fun quote(text: String): String =
        "\"" + text.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", " ") + "\""

    private data class CollapsedEdge(val from: String, val to: String, val testOnly: Boolean)
}
