package com.aalekh.aalekh.report.mainsequence

import com.aalekh.aalekh.model.MainSequenceReport
import com.aalekh.aalekh.model.MainSequenceZone
import com.aalekh.aalekh.model.ModuleMainSequence
import kotlinx.serialization.json.Json

/**
 * Renders a [MainSequenceReport] as the two local artefacts `aalekhMainSequence` writes:
 *
 * - [markdown] - a reviewable table of each module's abstractness (A), instability (I) and distance
 *   from the main sequence (D), worst first, with the off-sequence modules called out.
 * - [json] - the same data machine-readable.
 *
 * Both are pure string transforms - no Gradle, no I/O.
 */
public object MainSequenceReportGenerator {

    private val prettyJson = Json {
        prettyPrint = true
        encodeDefaults = true
    }

    /** Serialises the report to pretty-printed JSON. */
    public fun json(report: MainSequenceReport): String =
        prettyJson.encodeToString(MainSequenceReport.serializer(), report)

    /** Renders the report as a Markdown document. */
    public fun markdown(report: MainSequenceReport, projectName: String): String = buildString {
        appendLine("# $projectName - main sequence (abstractness vs instability)")
        appendLine()
        if (report.modules.isEmpty()) {
            appendLine(
                "_No countable type declarations were found, so abstractness could not be computed. " +
                    "This happens when no module has scannable Kotlin/Java source._"
            )
            return@buildString
        }
        appendLine(
            "_Generated by [Aalekh](https://github.com/shivathapaa/aalekh). Distance **D = |A + I - 1|** " +
                "measures how far a module sits from the ideal balance of abstractness and instability " +
                "(0 is on the line, 1 is a far corner). Abstractness is a coarse source-scan estimate._"
        )
        appendLine()
        appendLine("**Average distance from the main sequence: ${format(report.averageDistance)}**")
        appendLine()
        appendZones(report)
        appendTable(report)
    }

    private fun StringBuilder.appendZones(report: MainSequenceReport) {
        val pain = report.modules.filter { it.zone == MainSequenceZone.ZONE_OF_PAIN }
        val useless = report.modules.filter { it.zone == MainSequenceZone.ZONE_OF_USELESSNESS }
        appendLine("## Off the main sequence")
        appendLine()
        appendZoneList(
            "Zone of pain",
            "concrete **and** stable - rigid, hard to change, yet heavily depended upon",
            pain,
        )
        appendZoneList(
            "Zone of uselessness",
            "abstract **and** unstable - abstractions almost nothing depends on",
            useless,
        )
    }

    private fun StringBuilder.appendZoneList(title: String, blurb: String, modules: List<ModuleMainSequence>) {
        appendLine("### $title")
        appendLine()
        appendLine("_$blurb._")
        appendLine()
        if (modules.isEmpty()) {
            appendLine("_None._")
        } else {
            modules.forEach { m ->
                val coords = "A ${format(m.abstractness)}, I ${format(m.instability)}, D ${format(m.distance)}"
                appendLine("- `${m.path}` ($coords)")
            }
        }
        appendLine()
    }

    private fun StringBuilder.appendTable(report: MainSequenceReport) {
        appendLine("## All modules")
        appendLine()
        appendLine("| Module | Abstractness | Instability | Distance | Zone | Types (abstract/total) |")
        appendLine("|--------|-------------:|------------:|---------:|------|:----------------------:|")
        report.modules.forEach { m ->
            appendLine(
                "| `${m.path}` | ${format(m.abstractness)} | ${format(m.instability)} | ${format(m.distance)} " +
                    "| ${zoneLabel(m.zone)} | ${m.abstractTypes}/${m.abstractTypes + m.concreteTypes} |"
            )
        }
        appendLine()
    }

    private fun zoneLabel(zone: MainSequenceZone): String = when (zone) {
        MainSequenceZone.MAIN_SEQUENCE -> "on sequence"
        MainSequenceZone.ZONE_OF_PAIN -> "pain"
        MainSequenceZone.ZONE_OF_USELESSNESS -> "uselessness"
    }

    /** Two-decimal fixed formatting without locale dependence (e.g. `0.83`). */
    private fun format(value: Double): String {
        val hundredths = Math.round(value * HUNDRED).toInt()
        return "${hundredths / HUNDRED_INT}.${(hundredths % HUNDRED_INT).toString().padStart(2, '0')}"
    }

    private const val HUNDRED = 100.0
    private const val HUNDRED_INT = 100
}
