package com.aalekh.aalekh.report.temporal

import com.aalekh.aalekh.model.CoChange
import com.aalekh.aalekh.model.TemporalCouplingReport
import kotlinx.serialization.json.Json

/**
 * Renders a [TemporalCouplingReport] as the two local artefacts `aalekhTemporal` writes:
 *
 * - [markdown] - a human-reviewable, diffable report with hotspot / hidden-coupling / dead-structure
 *   tables, ready to commit or paste into a PR.
 * - [json] - the same data machine-readable, for a consumer's own tooling.
 *
 * Both are pure string transforms - no Gradle, no I/O.
 */
public object TemporalReportGenerator {

    private const val TOP_CO_CHANGES = 25

    private val prettyJson = Json {
        prettyPrint = true
        encodeDefaults = true
    }

    /** Serialises the report to pretty-printed JSON. */
    public fun json(report: TemporalCouplingReport): String =
        prettyJson.encodeToString(TemporalCouplingReport.serializer(), report)

    /** Renders the report as a Markdown document. */
    public fun markdown(report: TemporalCouplingReport, projectName: String): String = buildString {
        appendLine("# $projectName - temporal coupling")
        appendLine()
        if (report.commitsAnalyzed == 0) {
            appendLine(
                "_No git history was available, so temporal coupling could not be computed. " +
                    "This happens in a shallow clone or a repository with no commits._"
            )
            return@buildString
        }
        appendLine(
            "_Generated by [Aalekh](https://github.com/shivathapaa/aalekh) from the last " +
                "${report.commitsAnalyzed} commit(s) that touched a module. Temporal coupling shows " +
                "how the code actually changes together, independent of the declared dependency graph._"
        )
        appendLine()
        appendHiddenCoupling(report)
        appendDeadStructure(report)
        appendHotspots(report)
        appendTopCoChanges(report)
    }

    private fun StringBuilder.appendHiddenCoupling(report: TemporalCouplingReport) {
        appendLine("## Hidden coupling")
        appendLine()
        appendLine("Pairs that change together but declare **no** dependency - implicit coupling to review.")
        appendLine()
        if (report.hiddenCoupling.isEmpty()) {
            appendLine("_None detected._")
            appendLine()
            return
        }
        appendLine("| Module A | Module B | Shared commits | Degree |")
        appendLine("|----------|----------|---------------:|-------:|")
        report.hiddenCoupling.forEach { appendLine(coChangeRow(it, includeDeclared = false)) }
        appendLine()
    }

    private fun StringBuilder.appendDeadStructure(report: TemporalCouplingReport) {
        appendLine("## Dead structure")
        appendLine()
        appendLine("Declared edges whose modules both changed in the window but **never together** - review or remove.")
        appendLine()
        if (report.deadStructure.isEmpty()) {
            appendLine("_None detected._")
            appendLine()
            return
        }
        appendLine("| From | To |")
        appendLine("|------|----|")
        report.deadStructure.forEach { appendLine("| `${it.from}` | `${it.to}` |") }
        appendLine()
    }

    private fun StringBuilder.appendHotspots(report: TemporalCouplingReport) {
        appendLine("## Change hotspots")
        appendLine()
        appendLine("Most-committed modules - prime targets for refactoring and test hardening.")
        appendLine()
        appendLine("| Module | Commits |")
        appendLine("|--------|--------:|")
        report.churn.forEach { appendLine("| `${it.module}` | ${it.commits} |") }
        appendLine()
    }

    private fun StringBuilder.appendTopCoChanges(report: TemporalCouplingReport) {
        appendLine("## Top co-changing pairs")
        appendLine()
        appendLine("| Module A | Module B | Shared commits | Degree | Declared |")
        appendLine("|----------|----------|---------------:|-------:|:--------:|")
        report.coChanges.take(TOP_CO_CHANGES).forEach { appendLine(coChangeRow(it, includeDeclared = true)) }
        appendLine()
    }

    private fun coChangeRow(pair: CoChange, includeDeclared: Boolean): String {
        val degree = formatDegree(pair.degree)
        val base = "| `${pair.moduleA}` | `${pair.moduleB}` | ${pair.sharedCommits} | $degree |"
        return if (includeDeclared) "$base ${if (pair.declared) "yes" else "no"} |" else base
    }

    /** Two-decimal fixed formatting without locale dependence (e.g. `0.83`). */
    private fun formatDegree(degree: Double): String {
        val hundredths = Math.round(degree * HUNDRED).toInt()
        return "${hundredths / HUNDRED_INT}.${(hundredths % HUNDRED_INT).toString().padStart(2, '0')}"
    }

    private const val HUNDRED = 100.0
    private const val HUNDRED_INT = 100
}
