package com.aalekh.aalekh.report.mermaid

import com.aalekh.aalekh.model.ModuleDependencyGraph
import com.aalekh.aalekh.model.ModuleType

/**
 * Renders a [ModuleDependencyGraph] as a [Mermaid](https://mermaid.js.org) `graph` definition.
 *
 * Unlike the interactive HTML report or the binary SVG export, Mermaid output is **plain text**:
 * it diffs cleanly in pull requests and renders inline on GitHub, GitLab, and most IDEs wherever
 * it appears inside a ` ```mermaid ` fenced code block. Committing the generated file next to the
 * code turns the module graph into a reviewable, versioned artefact.
 *
 * Output shape:
 * - `graph TD` (top-down) with one node per module. Node ids are stable synthetic tokens
 *   (`n0`, `n1`, ...) assigned in sorted path order so the same graph always produces byte-identical
 *   output; the real module path is the visible label.
 * - Production edges are solid (`-->`); test-only edges are dashed (`-.->`).
 * - Each module type gets a `classDef` coloured with its report palette entry, so the rendered
 *   graph is colour-coded by module type.
 */
public object MermaidGraphGenerator {

    /**
     * Returns the raw Mermaid graph definition (no code fence). Suitable for a `.mmd` file or for
     * embedding inside a ` ```mermaid ` block yourself.
     */
    public fun generate(graph: ModuleDependencyGraph): String {
        val sortedModules = graph.modules.sortedBy { it.path }
        val idByPath = sortedModules.mapIndexed { index, module -> module.path to "n$index" }.toMap()

        val builder = StringBuilder()
        builder.appendLine("%% Generated by Aalekh - https://github.com/shivathapaa/aalekh")
        builder.appendLine("%% Solid arrows are production dependencies; dashed arrows are test-only.")
        builder.appendLine("graph TD")

        sortedModules.forEach { module ->
            val id = idByPath.getValue(module.path)
            builder.appendLine("  $id[\"${escapeLabel(module.path)}\"]")
        }

        collapseEdges(graph).forEach { edge ->
            val fromId = idByPath[edge.from] ?: return@forEach
            val toId = idByPath[edge.to] ?: return@forEach
            val arrow = if (edge.testOnly) "-.->" else "-->"
            builder.appendLine("  $fromId $arrow $toId")
        }

        appendTypeStyling(builder, sortedModules, idByPath)
        return builder.toString().trimEnd()
    }

    /**
     * Returns a complete Markdown document embedding the graph in a ` ```mermaid ` fenced block,
     * so the file renders as a diagram directly on GitHub. Use for a committed `graph.md`.
     */
    public fun generateMarkdown(graph: ModuleDependencyGraph, projectName: String): String =
        buildString {
            appendLine("# $projectName module graph")
            appendLine()
            appendLine("```mermaid")
            appendLine(generate(graph))
            appendLine("```")
        }

    /**
     * Collapses parallel edges between the same pair of modules into a single link. A pair with any
     * production edge renders solid; a pair connected only through test configurations renders dashed.
     */
    private fun collapseEdges(graph: ModuleDependencyGraph): List<CollapsedEdge> =
        graph.edges
            .filter { it.from != it.to }
            .groupBy { it.from to it.to }
            .map { (pair, edges) -> CollapsedEdge(pair.first, pair.second, testOnly = edges.all { it.isTest }) }
            .sortedWith(compareBy({ it.from }, { it.to }))

    private fun appendTypeStyling(
        builder: StringBuilder,
        modules: List<com.aalekh.aalekh.model.ModuleNode>,
        idByPath: Map<String, String>,
    ) {
        val modulesByType = modules.groupBy { it.type }
        ModuleType.entries.forEach { type ->
            val members = modulesByType[type] ?: return@forEach
            val className = type.name.lowercase()
            builder.appendLine("  classDef $className fill:${type.color},color:#ffffff,stroke:#00000033")
            val ids = members.map { idByPath.getValue(it.path) }.sorted().joinToString(",")
            builder.appendLine("  class $ids $className")
        }
    }

    /** Mermaid node labels are wrapped in double quotes; neutralise any embedded quote or newline. */
    private fun escapeLabel(text: String): String = text
        .replace("\"", "'")
        .replace("\n", " ")

    private data class CollapsedEdge(val from: String, val to: String, val testOnly: Boolean)
}
