package com.aalekh.aalekh.report.diff

import com.aalekh.aalekh.model.ArchitectureDiff
import com.aalekh.aalekh.model.LayerChange
import kotlinx.serialization.json.Json

/**
 * Renders an [ArchitectureDiff] as a pull-request comment.
 *
 * Architecture changes are invisible in a normal diff: adding one line to a `dependencies { }` block
 * can wire two subsystems together, and the review shows one line. This turns that into a paragraph a
 * reviewer reads without knowing the graph.
 *
 * Ordered by consequence rather than by kind - a new cycle first, then dependencies, then modules -
 * because a reviewer skims from the top and the first thing they see should be the thing most worth
 * their attention.
 */
// One small function per section of the comment plus the shared formatting helpers; the count tracks
// how many kinds of change a diff can report, not how many jobs this object does.
@Suppress("TooManyFunctions")
public object ArchitectureDiffReporter {

    private const val MAX_LISTED = 20

    private val json = Json {
        prettyPrint = true
        encodeDefaults = true
    }

    /** The diff as a Markdown document, ready to post as a pull-request comment. */
    public fun markdown(diff: ArchitectureDiff, projectName: String): String = buildString {
        appendLine("## Architecture change · $projectName")
        appendLine()

        if (diff.isEmpty) {
            appendLine("No architectural change. The module graph, its cycles, and its layer")
            appendLine("assignments are identical to the committed snapshot.")
            return@buildString
        }

        appendLine(headline(diff))
        appendLine()

        appendSection(
            "🔴 New dependency cycles",
            diff.newCycles,
            "These modules can no longer be built, tested, or reasoned about independently. " +
                "Run `aalekhCheck` for the exact dependency to remove.",
        ) { "`$it`" }

        appendSection(
            "✅ Cycles resolved",
            diff.resolvedCycles,
            "These modules are no longer part of a dependency cycle.",
        ) { "`$it`" }

        appendSection(
            "➕ Dependencies added",
            diff.addedEdges,
            "Each of these widens the blast radius of the module it points at.",
        ) { formatEdge(it) }

        appendSection(
            "➖ Dependencies removed",
            diff.removedEdges,
            null,
        ) { formatEdge(it) }

        appendSection("➕ Modules added", diff.addedModules, null) { "`$it`" }
        appendSection("➖ Modules removed", diff.removedModules, null) { "`$it`" }

        appendLayerChanges(diff)
        appendMetrics(diff)

        appendLine("<sub>Generated by [Aalekh](https://github.com/shivathapaa/aalekh) with ")
        appendLine("`aalekhDiff`, against the committed `aalekh-snapshot.json`. Run `aalekhSnapshot` ")
        appendLine("to accept these changes as the new baseline.</sub>")
    }

    /** The diff as machine-readable JSON, for a CI job that wants to gate on it. */
    public fun json(diff: ArchitectureDiff): String =
        json.encodeToString(ArchitectureDiff.serializer(), diff)

    /** One sentence summarising the change, so a reviewer knows whether to read on. */
    private fun headline(diff: ArchitectureDiff): String {
        val parts = buildList {
            if (diff.newCycles.isNotEmpty()) {
                add("**introduces a dependency cycle** across ${count(diff.newCycles.size, "module")}")
            }
            if (diff.addedEdges.isNotEmpty()) {
                add("adds ${count(diff.addedEdges.size, "dependency", "dependencies")}")
            }
            if (diff.removedEdges.isNotEmpty()) {
                add("removes ${count(diff.removedEdges.size, "dependency", "dependencies")}")
            }
            if (diff.addedModules.isNotEmpty()) add("adds ${count(diff.addedModules.size, "module")}")
            if (diff.removedModules.isNotEmpty()) add("removes ${count(diff.removedModules.size, "module")}")
            if (diff.layerChanges.isNotEmpty()) {
                add("moves ${count(diff.layerChanges.size, "module")} between layers")
            }
        }
        val summary = when {
            parts.isEmpty() -> "changes the project's structural metrics"
            parts.size == 1 -> parts.single()
            else -> parts.dropLast(1).joinToString(", ") + " and " + parts.last()
        }
        val verdict = if (diff.hasRegression) {
            " Worth a closer look before merging."
        } else {
            ""
        }
        return "This change $summary.$verdict"
    }

    private fun StringBuilder.appendLayerChanges(diff: ArchitectureDiff) {
        if (diff.layerChanges.isEmpty()) return
        appendLine("### ↔ Modules that changed layer")
        appendLine()
        appendLine(
            "A module moving between layers changes which rules apply to it, and which modules " +
                "are allowed to depend on it."
        )
        appendLine()
        diff.layerChanges.entries.take(MAX_LISTED).forEach { (path, change) ->
            appendLine("- `$path`: ${describeLayer(change)}")
        }
        appendOverflow(diff.layerChanges.size)
    }

    private fun StringBuilder.appendMetrics(diff: ArchitectureDiff) {
        if (diff.metricDeltas.isEmpty()) return
        appendLine("### Metrics")
        appendLine()
        appendLine("| Metric | Before | After | |")
        appendLine("|--------|-------:|------:|---|")
        diff.metricDeltas.toSortedMap().forEach { (name, delta) ->
            val direction = if (delta.isWorse) "worse" else "better"
            appendLine("| $name | ${number(delta.before)} | ${number(delta.after)} | $direction |")
        }
        appendLine()
    }

    private fun StringBuilder.appendSection(
        title: String,
        items: List<String>,
        note: String?,
        format: (String) -> String,
    ) {
        if (items.isEmpty()) return
        appendLine("### $title")
        appendLine()
        note?.let {
            appendLine(it)
            appendLine()
        }
        items.take(MAX_LISTED).forEach { appendLine("- ${format(it)}") }
        appendOverflow(items.size)
    }

    /**
     * Notes what was left out when a list is truncated.
     *
     * Silently showing the first twenty of two hundred would read as "there were twenty", which is
     * the kind of quiet truncation that makes a report untrustworthy.
     */
    private fun StringBuilder.appendOverflow(total: Int) {
        if (total > MAX_LISTED) {
            appendLine()
            appendLine(
                "<sub>… and ${total - MAX_LISTED} more; see `aalekh-diff.json` for the full list.</sub>"
            )
        }
        appendLine()
    }

    private fun formatEdge(key: String): String {
        val from = key.substringBefore('>')
        val to = key.substringAfter('>')
        return "`$from` → `$to`"
    }

    private fun describeLayer(change: LayerChange): String = when {
        change.before == null -> "now in **${change.after}** (was outside every declared layer)"
        change.after == null -> "left **${change.before}** and matches no declared layer now"
        else -> "**${change.before}** → **${change.after}**"
    }

    private fun number(value: Double): String =
        if (value == value.toLong().toDouble()) value.toLong().toString()
        else String.format(java.util.Locale.ROOT, "%.2f", value)

    private fun count(n: Int, singular: String, plural: String = singular + "s"): String =
        "$n ${if (n == 1) singular else plural}"
}
